server:
  port: 9090
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Aplica esta configuración a todas las rutas
            allowedOrigins: "http://localhost:4200" # Orígenes permitidos
            allowedMethods: # Métodos HTTP permitidos
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: # Cabeceras permitidas
              - Content-Type
              - Authorization
            allowCredentials: true # Soporte para cookies y autenticación HTTP
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: restaurant-user-microservice
          uri: lb://restaurant-user-microservice
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: restaurant-client-microservice
          uri: lb://restaurant-client-microservice
          predicates:
            - Path=/api/consumers/**
        - id: restaurant-table-microservice
          uri: lb://restaurant-table-microservice
          predicates:
            - Path=/api/tables/**
        - id: restaurant-booking-microservice
          uri: lb://restaurant-booking-microservice
          predicates:
            - Path=/api/bookings/**
        - id: restaurant-beverage-microservice
          uri: lb://restaurant-beverage-microservice
          predicates:
            - Path=/api/beverages/**
        - id: restaurant-course-microservice
          uri: lb://restaurant-course-microservice
          predicates:
            - Path=/api/courses/**
management:
  tracing:
    sampling:
      probability: 1.0