eviden:
  config:
    db:
      name: proyectodb
server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
spring:
  application:
    name: restaurant-eureka-microservice
  datasource:
   url: jdbc:mysql://localhost:3306/${eviden.config.db.name}
   username: micro
   password: Tc_Yk[KUp0adN/1o
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true