eviden:
  config:
    db:
      name: proyectodb
server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/${eviden.config.db.name}
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/idp-realm
management:
  tracing:
    sampling:
      probability: 1.0