server:
  port: 9090
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/proyectoBackend
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/proyectoBackend/protocol/openid-connect/auth
            user-info-uri: http://localhost:8080/realms/proyectoBackend/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8080/realms/proyectoBackend/protocol/openid-connect/token
            issuer-uri: http://localhost:8080/realms/proyectoBackend
        registration:
          mi-cliente:
            provider: keycloak
            client-id: mi-cliente
            client-secret: nsdBRfgpWGQWohMruqd7NyOB5z1HWvte
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/mi-cliente
            scope: openid
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: restaurant-user-microservice
          uri: lb://restaurant-user-microservice
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: restaurant-client-microservice
          uri: lb://restaurant-client-microservice
          predicates:
            - Path=/api/consumers/**
        - id: restaurant-table-microservice
          uri: lb://restaurant-table-microservice
          predicates:
            - Path=/api/tables/**
        - id: restaurant-booking-microservice
          uri: lb://restaurant-booking-microservice
          predicates:
            - Path=/api/bookings/**
        - id: restaurant-beverage-microservice
          uri: lb://restaurant-beverage-microservice
          predicates:
            - Path=/api/beverages/**
        - id: restaurant-course-microservice
          uri: lb://restaurant-course-microservice
          predicates:
            - Path=/api/courses/**
management:
  tracing:
    sampling:
      probability: 1.0