server:
  port: 9000
  
spring:
  application:
    name: restaurant-config-microservice
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/rpjdcode/restaurant-microservices
          search-paths: /restaurant-config-microservice/config-data
          username: rpjdcode
          password: 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
